import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const toolsDirectory = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(toolsDirectory, '..');
const domain = fs.readFileSync(path.join(root, 'CNAME'), 'utf8').trim();
const siteUrl = `https://${domain}`;
const siteName = 'Lumina · Luminox';
const organizationId = `${siteUrl}/#organization`;
const websiteId = `${siteUrl}/#website`;
const applicationId = `${siteUrl}/#luminox`;
const organizationLogo = `${siteUrl}/assets/brand/lumina-seal-256.png`;
const installUrl = 'https://discord.com/oauth2/authorize?client_id=1520561230648049965&permissions=395541081168&integration_type=0&scope=bot+applications.commands';
const discordUrl = 'https://discord.gg/9BTRjtjnU8';
const guildUrl = 'https://www.tibia.com/community/?subtopic=guilds&page=view&GuildName=Lumina';
const generatedMarkerStart = '<!-- SEO ENHANCEMENTS: generated by tools/build-seo.mjs -->';
const generatedMarkerEnd = '<!-- /SEO ENHANCEMENTS -->';
const socialDirectory = path.join(root, 'assets', 'social');
const today = new Date().toISOString().slice(0, 10);
const stylesheetHref = 'styles.css?v=20260721-3';

const familyThemes = {
  home: { label: 'LUMINA · LUMINOX', primary: '#f7c84b', secondary: '#a971ff', footer: 'TIBIA GUILD · DISCORD BOT' },
  guild: { label: 'LUMINA GUILD', primary: '#f7c84b', secondary: '#63e6a6', footer: 'TIBIA · SECURA · INTERNATIONAL' },
  bot: { label: 'LUMINOX', primary: '#a971ff', secondary: '#52d7ff', footer: 'DISCORD GUILD BOT' },
  docs: { label: 'LUMINOX DOCS', primary: '#52d7ff', secondary: '#a971ff', footer: 'GUIDES · SETUP · REFERENCE' },
  pricing: { label: 'LUMINOX PLANS', primary: '#f7c84b', secondary: '#ff6c8f', footer: 'FREE · CORE · GROWTH · SCALE' },
  blog: { label: 'LUMINA JOURNAL', primary: '#ff6c8f', secondary: '#f7c84b', footer: 'NEWS · STORIES · COMMUNITY' },
  contact: { label: 'TALK WITH US', primary: '#52d7ff', secondary: '#63e6a6', footer: 'GUILD · PRODUCT · SUPPORT' },
  legal: { label: 'LUMINA LEGAL', primary: '#52d7ff', secondary: '#f7c84b', footer: 'TERMS · PRIVACY · COOKIES' }
};

const planOffers = [
  ['universal-free', 'Luminox Universal Free', '0', 'universal'],
  ['universal-core', 'Luminox Universal Core', '4.99', 'universal'],
  ['universal-growth', 'Luminox Universal Growth', '9.99', 'universal'],
  ['universal-scale', 'Luminox Universal Scale', '19.99', 'universal'],
  ['community-free', 'Luminox Community Free', '0', 'community'],
  ['community-core', 'Luminox Community Core', '7.99', 'community'],
  ['community-growth', 'Luminox Community Growth', '14.99', 'community'],
  ['community-scale', 'Luminox Community Scale', '29.99', 'community']
];

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function escapeAttribute(value) {
  return String(value)
    .replace(/&(?!(?:[a-z][a-z0-9]+|#\d+|#x[a-f0-9]+);)/gi, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function escapeXml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function decodeEntities(value) {
  return String(value)
    .replace(/&amp;/gi, '&')
    .replace(/&quot;/gi, '"')
    .replace(/&#39;|&apos;/gi, "'")
    .replace(/&middot;/gi, '·')
    .replace(/&euro;/gi, '€')
    .replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(Number(code)))
    .replace(/&#x([a-f0-9]+);/gi, (_, code) => String.fromCodePoint(Number.parseInt(code, 16)));
}

function plainText(value) {
  return decodeEntities(String(value || '').replace(/<[^>]*>/g, ' ')).replace(/\s+/g, ' ').trim();
}

function extract(source, expression) {
  return expression.exec(source)?.[1]?.trim() || '';
}

function canonicalFor(file) {
  return file === 'index.html' ? `${siteUrl}/` : `${siteUrl}/${file}`;
}

function socialFileFor(file) {
  return file === 'index.html' ? 'home.png' : `${path.basename(file, '.html')}.png`;
}

function classify(file) {
  if (file === 'index.html') return 'home';
  if (file === 'contact.html') return 'contact';
  if (file === 'legal.html') return 'legal';
  if (file === 'pricing.html' || file === 'pricing-faq.html' || file === 'guarantee.html') return 'pricing';
  if (file === 'blog.html') return 'blog';
  if (file === 'gallery.html' || file === 'guild.html' || file.startsWith('guild-')) return 'guild';
  if (file === 'docs.html' || file === 'commands.html' || file === 'setup.html' || file === 'changelog.html' || file === 'roadmap.html' || file.startsWith('docs-')) return 'docs';
  return 'bot';
}

function labelFor(file, title, h1) {
  const fixed = {
    'features.html': 'Bot',
    'docs.html': 'Documentation',
    'guild.html': 'Guild',
    'pricing.html': 'Pricing',
    'blog.html': 'Blog',
    'gallery.html': 'Gallery',
    'contact.html': 'Contact',
    'commands.html': 'Command Reference',
    'setup.html': 'Installation',
    'changelog.html': 'Changelog',
    'roadmap.html': 'Roadmap',
    'legal.html': 'Legal'
  };
  if (fixed[file]) return fixed[file];
  const candidate = plainText(title)
    .replace(/^Lumina\s*[·|:-]\s*/i, '')
    .replace(/^Luminox\s+/i, '')
    .replace(/\s*\|\s*.*$/, '')
    .trim();
  return candidate || plainText(h1) || path.basename(file, '.html');
}

function breadcrumbsFor(page) {
  if (page.file === 'index.html') return [];
  const crumbs = [{ name: 'Home', item: `${siteUrl}/` }];
  const familyRoot = {
    guild: { name: 'Guild', item: `${siteUrl}/guild.html` },
    bot: { name: 'Bot', item: `${siteUrl}/features.html` },
    docs: { name: 'Documentation', item: `${siteUrl}/docs.html` },
    pricing: { name: 'Pricing', item: `${siteUrl}/pricing.html` },
    blog: { name: 'Guild', item: `${siteUrl}/guild.html` },
    contact: null,
    legal: null
  }[page.family];

  if (familyRoot && familyRoot.item !== page.canonical) crumbs.push(familyRoot);
  crumbs.push({ name: page.label, item: page.canonical });
  return crumbs;
}

function organizationSchema() {
  return {
    '@type': 'Organization',
    '@id': organizationId,
    name: 'Lumina',
    alternateName: 'Lumina Guild',
    url: `${siteUrl}/`,
    logo: {
      '@type': 'ImageObject',
      url: organizationLogo,
      width: 256,
      height: 256
    },
    description: 'International Tibia guild on Secura focused on teamwork, progression, organized community life and the Luminox Discord guild bot.',
    sameAs: [guildUrl, discordUrl]
  };
}

function freeOffer() {
  return {
    '@type': 'Offer',
    name: 'Luminox Free',
    price: '0',
    priceCurrency: 'EUR',
    availability: 'https://schema.org/InStock',
    url: `${siteUrl}/pricing.html`,
    seller: { '@id': organizationId }
  };
}

function applicationSchema(offers = freeOffer()) {
  return {
    '@type': 'SoftwareApplication',
    '@id': applicationId,
    name: 'Luminox',
    alternateName: 'Luminox Discord Guild Bot',
    url: `${siteUrl}/features.html`,
    image: `${siteUrl}/assets/social/features.png`,
    applicationCategory: 'CommunicationApplication',
    applicationSubCategory: 'Discord guild management bot',
    operatingSystem: 'Any',
    runtimePlatform: 'Discord',
    description: 'Discord guild bot for verified identities, events, Loyalty, GuildBank, private support, moderation and live guild intelligence.',
    isAccessibleForFree: true,
    installUrl,
    softwareHelp: `${siteUrl}/docs.html`,
    releaseNotes: `${siteUrl}/changelog.html`,
    featureList: `${siteUrl}/features.html`,
    offers,
    publisher: { '@id': organizationId }
  };
}

function pricingOffers() {
  return planOffers.map(([sku, name, price, edition]) => ({
    '@type': 'Offer',
    '@id': `${siteUrl}/pricing.html#${sku}`,
    sku,
    name,
    category: `${edition[0].toUpperCase()}${edition.slice(1)} Edition`,
    price,
    priceCurrency: 'EUR',
    availability: 'https://schema.org/InStock',
    url: `${siteUrl}/pricing.html?edition=${edition}#premium-tiers`,
    priceSpecification: {
      '@type': 'UnitPriceSpecification',
      price,
      priceCurrency: 'EUR',
      billingDuration: 'P1M',
      unitText: 'MONTH'
    },
    seller: { '@id': organizationId },
    itemOffered: { '@id': applicationId }
  }));
}

function enhancedSchema(page) {
  const graph = [];
  const breadcrumbs = breadcrumbsFor(page);
  if (breadcrumbs.length >= 2) {
    graph.push({
      '@type': 'BreadcrumbList',
      '@id': `${page.canonical}#breadcrumb`,
      itemListElement: breadcrumbs.map((crumb, index) => ({
        '@type': 'ListItem',
        position: index + 1,
        name: crumb.name,
        item: crumb.item
      }))
    });
  }

  if (page.family === 'guild' || page.family === 'blog' || page.file === 'index.html') {
    graph.push(organizationSchema());
  }

  if (page.family === 'bot') {
    graph.push(organizationSchema(), applicationSchema());
  }

  if (page.family === 'docs') {
    graph.push(
      organizationSchema(),
      applicationSchema(),
      {
        '@type': 'TechArticle',
        '@id': `${page.canonical}#article`,
        url: page.canonical,
        headline: page.h1 || page.title,
        description: page.description,
        image: page.socialUrl,
        mainEntityOfPage: { '@id': `${page.canonical}#webpage` },
        isPartOf: { '@id': websiteId },
        about: { '@id': applicationId },
        author: { '@id': organizationId },
        publisher: { '@id': organizationId },
        dateModified: page.lastModified,
        inLanguage: 'en'
      }
    );
  }

  if (page.family === 'pricing') {
    const offers = pricingOffers();
    const offerReferences = offers.map((offer) => ({ '@id': offer['@id'] }));
    graph.push(
      organizationSchema(),
      applicationSchema(offerReferences),
      {
        '@type': 'OfferCatalog',
        '@id': `${siteUrl}/pricing.html#catalog`,
        name: 'Luminox Free and Premium plans',
        url: `${siteUrl}/pricing.html`,
        itemListElement: offers
      }
    );
  }

  if (page.family === 'contact') graph.push(organizationSchema(), applicationSchema());
  if (page.family === 'legal') graph.push(organizationSchema(), applicationSchema());

  return {
    '@context': 'https://schema.org',
    '@graph': graph
  };
}

function replaceMeta(source, attribute, key, content) {
  const expression = new RegExp(`<meta\\s+[^>]*${attribute}=["']${escapeRegExp(key)}["'][^>]*>`, 'i');
  const tag = `<meta ${attribute}="${key}" content="${escapeAttribute(content)}">`;
  if (expression.test(source)) return source.replace(expression, tag);
  return source.replace('</head>', `  ${tag}\n</head>`);
}

function ensureLink(source, rel, href, extra = '') {
  const expression = new RegExp(`<link\\s+[^>]*rel=["']${escapeRegExp(rel)}["'][^>]*>`, 'i');
  const tag = `<link rel="${rel}"${extra} href="${escapeAttribute(href)}">`;
  if (expression.test(source)) return source.replace(expression, tag);
  return source.replace('</head>', `  ${tag}\n</head>`);
}

function ensureFaviconLinks(source) {
  const iconExpression = /^[ \t]*<link\b(?=[^>]*\brel=["'](?:icon|apple-touch-icon)["'])[^>]*>[ \t]*(?:\r?\n)?/gim;
  const iconBlock = [
    '  <link rel="icon" type="image/svg+xml" sizes="any" href="assets/brand/favicon-dark.svg">',
    '  <link rel="icon" type="image/png" sizes="32x32" href="assets/brand/favicon-32x32.png">',
    '  <link rel="icon" type="image/png" sizes="16x16" href="assets/brand/favicon-16x16.png">',
    '  <link rel="apple-touch-icon" sizes="180x180" href="assets/brand/apple-touch-icon.png">'
  ].join('\n');
  const cleaned = source.replace(iconExpression, '');
  const manifestIndex = cleaned.search(/^[ \t]*<link\s+rel=["']manifest["']/im);
  if (manifestIndex >= 0) return `${cleaned.slice(0, manifestIndex)}${iconBlock}\n${cleaned.slice(manifestIndex)}`;
  return cleaned.replace('</head>', `${iconBlock}\n</head>`);
}

function addEnhancementBlock(source, page) {
  const expression = new RegExp(`${escapeRegExp(generatedMarkerStart)}[\\s\\S]*?${escapeRegExp(generatedMarkerEnd)}\\s*`, 'i');
  const rssLink = page.file === 'index.html' || page.file === 'blog.html'
    ? `\n  <link rel="alternate" type="application/rss+xml" title="Lumina Guild Blog" href="${siteUrl}/feed.xml">`
    : '';
  const block = `${generatedMarkerStart}\n  <meta name="author" content="Lumina Guild">\n  <meta name="application-name" content="Lumina · Luminox">${rssLink}\n  <script type="application/ld+json" data-seo-enhanced>${JSON.stringify(enhancedSchema(page))}</script>\n  ${generatedMarkerEnd}\n  `;
  const cleaned = source.replace(expression, '');
  const stylesheetIndex = cleaned.search(/<link\s+rel=["']stylesheet["']/i);
  if (stylesheetIndex >= 0) return `${cleaned.slice(0, stylesheetIndex)}${block}${cleaned.slice(stylesheetIndex)}`;
  return cleaned.replace('</head>', `  ${block}</head>`);
}

function updateHead(source, page) {
  let output = source;
  output = replaceMeta(output, 'name', 'viewport', 'width=device-width, initial-scale=1, viewport-fit=cover');
  output = replaceMeta(output, 'name', 'theme-color', '#090d19');
  output = replaceMeta(output, 'property', 'og:image', page.socialUrl);
  output = replaceMeta(output, 'property', 'og:image:secure_url', page.socialUrl);
  output = replaceMeta(output, 'property', 'og:image:type', 'image/png');
  output = replaceMeta(output, 'property', 'og:image:width', '1200');
  output = replaceMeta(output, 'property', 'og:image:height', '630');
  output = replaceMeta(output, 'property', 'og:image:alt', page.socialAlt);
  output = replaceMeta(output, 'name', 'twitter:card', 'summary_large_image');
  output = replaceMeta(output, 'name', 'twitter:image', page.socialUrl);
  output = replaceMeta(output, 'name', 'twitter:image:alt', page.socialAlt);
  output = ensureLink(output, 'stylesheet', stylesheetHref);
  output = ensureFaviconLinks(output);
  output = ensureLink(output, 'manifest', 'site.webmanifest');
  output = addEnhancementBlock(output, page);
  return output;
}

function wrapText(value, maxCharacters, maxLines) {
  const words = plainText(value).split(/\s+/).filter(Boolean);
  const lines = [];
  let current = '';
  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length <= maxCharacters || !current) {
      current = next;
      continue;
    }
    lines.push(current);
    current = word;
    if (lines.length === maxLines - 1) break;
  }
  if (current && lines.length < maxLines) lines.push(current);
  const consumed = lines.join(' ').length;
  if (consumed < plainText(value).length && lines.length > 0) {
    lines[lines.length - 1] = `${lines[lines.length - 1].replace(/[.,;:!?\s]+$/, '')}…`;
  }
  return lines;
}

function textLines(lines, x, y, lineHeight, attributes = '') {
  return lines.map((line, index) => `<text x="${x}" y="${y + (index * lineHeight)}" ${attributes}>${escapeXml(line)}</text>`).join('');
}

async function generateSocialCard(page, sealData) {
  const theme = familyThemes[page.family];
  const titleLines = wrapText(page.title, 27, 3);
  const descriptionLines = wrapText(page.description, 62, 2);
  const layout = titleLines.length >= 3
    ? { titleSize: 58, titleLineHeight: 64, titleStart: 282, descriptionStart: 475 }
    : titleLines.length === 2
      ? { titleSize: 68, titleLineHeight: 78, titleStart: 286, descriptionStart: 442 }
      : { titleSize: 72, titleLineHeight: 82, titleStart: 300, descriptionStart: 390 };
  const svg = `
  <svg width="1200" height="630" viewBox="0 0 1200 630" xmlns="http://www.w3.org/2000/svg">
    <defs>
      <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#070a13"/><stop offset="0.52" stop-color="#0b1020"/><stop offset="1" stop-color="#080b16"/></linearGradient>
      <radialGradient id="glowA"><stop stop-color="${theme.primary}" stop-opacity="0.26"/><stop offset="1" stop-color="${theme.primary}" stop-opacity="0"/></radialGradient>
      <radialGradient id="glowB"><stop stop-color="${theme.secondary}" stop-opacity="0.2"/><stop offset="1" stop-color="${theme.secondary}" stop-opacity="0"/></radialGradient>
      <linearGradient id="line" x1="0" y1="0" x2="1" y2="0"><stop stop-color="${theme.primary}"/><stop offset="1" stop-color="${theme.secondary}"/></linearGradient>
      <filter id="shadow"><feGaussianBlur stdDeviation="18"/></filter>
    </defs>
    <rect width="1200" height="630" rx="0" fill="url(#bg)"/>
    <circle cx="1030" cy="94" r="320" fill="url(#glowB)"/>
    <circle cx="103" cy="612" r="330" fill="url(#glowA)"/>
    <path d="M740 72 C910 142 875 338 1120 378" fill="none" stroke="${theme.secondary}" stroke-opacity="0.16" stroke-width="2"/>
    <path d="M760 92 C930 162 895 358 1140 398" fill="none" stroke="${theme.primary}" stroke-opacity="0.12" stroke-width="1"/>
    <g opacity="0.24" fill="none" stroke="url(#line)"><circle cx="1022" cy="318" r="145"/><circle cx="1022" cy="318" r="98"/><path d="M877 318h290M1022 173v290"/></g>
    <rect x="43" y="42" width="1114" height="546" rx="32" fill="none" stroke="url(#line)" stroke-opacity="0.36"/>
    <rect x="72" y="66" width="78" height="78" rx="39" fill="#080b16" stroke="${theme.primary}" stroke-opacity="0.58"/>
    <image href="data:image/png;base64,${sealData}" x="77" y="71" width="68" height="68" preserveAspectRatio="xMidYMid meet"/>
    <text x="172" y="104" fill="#ffffff" font-family="Arial, Helvetica, sans-serif" font-size="30" font-weight="800" letter-spacing="2">LUMINA</text>
    <text x="172" y="132" fill="#aeb7ca" font-family="Arial, Helvetica, sans-serif" font-size="16" font-weight="700" letter-spacing="3">GUILDLUMINA.COM</text>
    <rect x="72" y="172" width="${Math.max(230, theme.label.length * 15 + 55)}" height="42" rx="21" fill="${theme.primary}" fill-opacity="0.1" stroke="${theme.primary}" stroke-opacity="0.5"/>
    <text x="94" y="199" fill="${theme.primary}" font-family="Arial, Helvetica, sans-serif" font-size="17" font-weight="800" letter-spacing="3">${escapeXml(theme.label)}</text>
    ${textLines(titleLines, 72, layout.titleStart, layout.titleLineHeight, `fill="#f7f8fc" font-family="Arial, Helvetica, sans-serif" font-size="${layout.titleSize}" font-weight="800" letter-spacing="-2"`)}
    ${textLines(descriptionLines, 74, layout.descriptionStart, 31, 'fill="#b8c0d2" font-family="Arial, Helvetica, sans-serif" font-size="23" font-weight="500"')}
    <rect x="72" y="548" width="1056" height="2" fill="url(#line)" opacity="0.6"/>
    <text x="74" y="579" fill="#d8dcea" font-family="Arial, Helvetica, sans-serif" font-size="16" font-weight="700" letter-spacing="2">${escapeXml(theme.footer)}</text>
    <circle cx="1118" cy="578" r="6" fill="${theme.secondary}"/><circle cx="1097" cy="578" r="4" fill="${theme.primary}"/>
  </svg>`;

  await sharp(Buffer.from(svg))
    .png({ compressionLevel: 9, palette: true, quality: 92 })
    .toFile(path.join(socialDirectory, socialFileFor(page.file)));
}

function getModifiedDate(file) {
  try {
    const status = execFileSync('git', ['status', '--porcelain', '--', file], { cwd: root, encoding: 'utf8' }).trim();
    if (status) return today;
    const committed = execFileSync('git', ['log', '-1', '--format=%cs', '--', file], { cwd: root, encoding: 'utf8' }).trim();
    return committed || today;
  } catch {
    return today;
  }
}

function imageEntriesFor(page, source) {
  const entries = [{ loc: page.socialUrl, title: `${page.title} social preview` }];
  for (const match of source.matchAll(/<img\b([^>]*)>/gi)) {
    const attributes = match[1];
    const src = /\bsrc=["']([^"']+)["']/i.exec(attributes)?.[1]?.split(/[?#]/)[0] || '';
    const alt = /\balt=["']([^"']+)["']/i.exec(attributes)?.[1] || '';
    if (!src || !alt || /^(?:https?:|data:)/i.test(src) || !src.startsWith('assets/') || src.startsWith('assets/brand/')) continue;
    entries.push({ loc: `${siteUrl}/${src}`, title: plainText(alt) });
    if (entries.length >= 6) break;
  }
  return [...new Map(entries.map((entry) => [entry.loc, entry])).values()];
}

function buildSitemap(pages) {
  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">'
  ];
  for (const page of pages) {
    lines.push('  <url>');
    lines.push(`    <loc>${escapeXml(page.canonical)}</loc>`);
    lines.push(`    <lastmod>${page.lastModified}</lastmod>`);
    for (const image of page.images) {
      lines.push('    <image:image>');
      lines.push(`      <image:loc>${escapeXml(image.loc)}</image:loc>`);
      lines.push(`      <image:title>${escapeXml(image.title)}</image:title>`);
      lines.push('    </image:image>');
    }
    lines.push('  </url>');
  }
  lines.push('</urlset>', '');
  fs.writeFileSync(path.join(root, 'sitemap.xml'), lines.join('\n'));
}

function buildFeed() {
  const sourcePath = path.join(root, 'data', 'blog-posts.json');
  const data = JSON.parse(fs.readFileSync(sourcePath, 'utf8'));
  const posts = (Array.isArray(data.posts) ? data.posts : [])
    .filter((post) => post?.visible !== false)
    .sort((left, right) => Date.parse(right.publishedAt || 0) - Date.parse(left.publishedAt || 0));
  const buildDate = posts[0]?.updatedAt || posts[0]?.publishedAt || `${today}T00:00:00.000Z`;
  const items = posts.map((post) => {
    const anchor = String(post.id || '').toLowerCase();
    const link = `${siteUrl}/blog.html#${encodeURIComponent(anchor)}`;
    return [
      '    <item>',
      `      <title>${escapeXml(post.title)}</title>`,
      `      <link>${escapeXml(link)}</link>`,
      `      <guid isPermaLink="true">${escapeXml(link)}</guid>`,
      `      <pubDate>${new Date(post.publishedAt).toUTCString()}</pubDate>`,
      `      <dc:creator>${escapeXml(post.author || 'Lumina Guild')}</dc:creator>`,
      `      <category>${escapeXml(post.category || 'Guild journal')}</category>`,
      `      <description>${escapeXml(post.excerpt || '')}</description>`,
      '    </item>'
    ].join('\n');
  });
  const feed = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">',
    '  <channel>',
    '    <title>Lumina Guild Blog</title>',
    `    <link>${siteUrl}/blog.html</link>`,
    '    <description>Guild news, Tibia stories, events, roleplay and community updates from Lumina on Secura.</description>',
    '    <language>en</language>',
    `    <lastBuildDate>${new Date(buildDate).toUTCString()}</lastBuildDate>`,
    `    <atom:link href="${siteUrl}/feed.xml" rel="self" type="application/rss+xml"/>`,
    ...items,
    '  </channel>',
    '</rss>',
    ''
  ].join('\n');
  fs.writeFileSync(path.join(root, 'feed.xml'), feed);
}

async function main() {
  fs.mkdirSync(socialDirectory, { recursive: true });
  const files = fs.readdirSync(root)
    .filter((file) => file.endsWith('.html') && file !== '404.html')
    .sort((left, right) => left === 'index.html' ? -1 : right === 'index.html' ? 1 : left.localeCompare(right));
  const sealData = fs.readFileSync(path.join(root, 'assets', 'brand', 'lumina-seal-256.png')).toString('base64');
  const pages = files.map((file) => {
    const source = fs.readFileSync(path.join(root, file), 'utf8');
    const title = plainText(extract(source, /<title>([\s\S]*?)<\/title>/i));
    const description = plainText(extract(source, /<meta\s+name=["']description["']\s+content=["']([^"']+)["']/i));
    const h1 = plainText(extract(source, /<h1\b[^>]*>([\s\S]*?)<\/h1>/i));
    const family = classify(file);
    const canonical = canonicalFor(file);
    const socialUrl = `${siteUrl}/assets/social/${socialFileFor(file)}`;
    const lastModified = getModifiedDate(file);
    return {
      file,
      source,
      title,
      description,
      h1,
      family,
      canonical,
      socialUrl,
      socialAlt: `${title} — official GuildLumina.com preview`,
      label: labelFor(file, title, h1),
      lastModified
    };
  });

  for (const page of pages) {
    const output = updateHead(page.source, page);
    fs.writeFileSync(path.join(root, page.file), output);
    page.images = imageEntriesFor(page, output);
    await generateSocialCard(page, sealData);
  }

  const notFoundPath = path.join(root, '404.html');
  if (fs.existsSync(notFoundPath)) {
    const source = fs.readFileSync(notFoundPath, 'utf8');
    let output = replaceMeta(source, 'name', 'viewport', 'width=device-width, initial-scale=1, viewport-fit=cover');
    output = replaceMeta(output, 'name', 'theme-color', '#090d19');
    output = ensureLink(output, 'stylesheet', stylesheetHref);
    output = ensureFaviconLinks(output);
    fs.writeFileSync(notFoundPath, ensureLink(output, 'manifest', 'site.webmanifest'));
  }

  buildSitemap(pages);
  buildFeed();
  process.stdout.write(`SEO generated for ${pages.length} public pages on ${siteUrl}.\n`);
}

await main();
